### PR TITLE
Feature/dc 1509 migrate docs to asciidoc

### PR DESCRIPTION
**Pull request by oleksii-symon-corva-ai**
### Rationale
We want to have robust documentation.

[Docs example](https://github.com/corva-ai/python-sdk/files/6390591/index.zip).

The docs are not hosted yet, but to generate and see them locally [use "Generate docs" section](https://github.com/corva-ai/python-sdk/blob/feature/dc-1509_migrate-docs-to-asciidoc/docs/index.adoc#84-generate-docs).

### Changes
* Migrated docs to [asciidoc](https://docs.asciidoctor.org/asciidoc/latest/) format
* Every code snippet from docs lives in separate file now and is automatically tested
* Deleted caching in CI as boost was only 2sec and cache lead to CI failing

[JIRA ticket](https://corvaqa.atlassian.net/browse/DC-1509)

#### TODO
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by finomayato** [comment]
Why asciidoc?

**Comment by oleksii-symon-corva-ai** [comment]
> Why asciidoc?

1. Syntax is more concise than (or at least as concise as) `markdown`.
2. Syntax is similar to `markdown`, which makes it easy for future contributors to comprehend.
3. Syntax is simpler than `.rst`.
4. It is **standardized** and has many useful features, that I needed, out of the box, like: admonitions, file includes, auto toc, code callouts. Those features are missing in `markdown`, but can be added through extensions.
5. Asciidoc documentation is clear and good.
6. Resulting documentation looks good.
7. There are plugins for different tools (pycharm, vscode, etc.)

https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/

**Review by finomayato — APPROVED** [review]
`rst` more widely used judging from my experience.
Though, if the project's stakeholders are OK with it - I'm onboard

**Review by ville — APPROVED** [review]
Looks great!

**Pull request merged**
